name: Build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: build
        run: yarn run build
      - name: deploy to laliyun
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "build"
          REMOTE_HOST: "guojianbo.top"
          REMOTE_USER: "root"
          TARGET: "/root/github-actions/simulator-macos"
        
